// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bookmark struct {
	UserID  string `json:"userId"`
	Private bool   `json:"private"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Token    int    `json:"token"`
}
